project:
  type: website
  resources:
    - resources

website:
  title: "üå∂Ô∏è"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  #page-footer: "Made with ‚ù§Ô∏è and Quarto"
  navbar:
    right:
    # - text: Home
    #   href: index.qmd
      - text: Extracurriculars
        href: extracurriculars/index.qmd
      - text: CV  
        href: cv/index.qmd
    # - text: Experience
    #   href: experience/index.qmd
    # - text: Education
    #   href: education/index.qmd
      
format:
  html:
    theme: [yeti, styles.scss]

